Communication between cli and daemon
polydrive/polydrive pull request #38
Opened 2022-03-22 12:03 UTC by JeremyLARDENOIS

Close #21

2022-03-24 09:34 UTC, AlexandreBrg requested changes
Nice work, working great on Ubuntu

2022-03-24 09:34 UTC, AlexandreBrg commented on client/src/agent/list.rs
>          log::info!("This should print the files");
Please remove this line, it's not useful

2022-03-24 09:34 UTC, AlexandreBrg commented on client/src/main.rs
> +                //     .to_string();
Please remove, not useful

2022-03-24 09:41 UTC, AlexandreBrg commented
* Please handle the deletion of `polydrive.sock` file in order to have gracefull shutdown.  SIGKILL + SIGINT 
* Make `cargo test` run onto `ubuntu 18/21` and `macOs 11`, see [github-env](https://github.com/actions/virtual-environments) for more infos 
* Add a test in `main.rs` to test whether the socket is working properly

2022-04-12 18:08 UTC, AlexandreBrg commented
Hi @JeremyLARDENOIS, @thomasgouveia finished your PR for the cli & communication with sockets. Your help was precious for his work. However, can you now focus yourself on testing if sockets are working properly in tests ? Even though we talked that we might not need it, it should be a good exercie for you to do that. 

There are [macros](https://doc.rust-lang.org/core/arch/index.html) to test for each platform you run tests on. Use them in order to have tests on this feature.

2022-04-12 20:58 UTC, JeremyLARDENOIS commented
Ubuntu 21 doesn't exists in github actions https://github.com/actions/virtual-environments

2022-04-13 06:55 UTC, JeremyLARDENOIS commented
@AlexandreBrg which part do you want that i remove so ?

2022-04-20 06:23 UTC, closed without merging